POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "diegoparking@parkease.com",
    "password": "12345678"
}
### logout
POST http://localhost:3001/api/auth/logout
Content-Type: application/json
### probar el verify-token
GET http://localhost:3001/api/branch/profile
Content-Type: application/json
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjA1NTc3MjZmYWIxMjMxZmEyZGNjNTcyMWExMDgzZGE2ODBjNGE3M2YiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcGFya2Vhc2UtMjA1ODQiLCJhdWQiOiJwYXJrZWFzZS0yMDU4NCIsImF1dGhfdGltZSI6MTc1ODcxMDg2NSwidXNlcl9pZCI6Ik5hU2E3bXRiYmNNNTdsVXAybjBMYnhIUmpYQTIiLCJzdWIiOiJOYVNhN210YmJjTTU3bFVwMm4wTGJ4SFJqWEEyIiwiaWF0IjoxNzU4NzEwODY1LCJleHAiOjE3NTg3MTQ0NjUsImVtYWlsIjoiZGllZ29wYXJraW5nQHBhcmtlYXNlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJkaWVnb3BhcmtpbmdAcGFya2Vhc2UuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.jjp5EoPeCYmbtIwAbDzDtAXbpg5omyviccplAzL6QuqS7vFRpQ561v9y9YCigo4mk3TnTobeVwGQ8WYhNHE8PtnLEKdVPnOvSm3Clb4KxcqUyDBNqoQwF8W63X8xkZ--DbHvU-u8LAbIlbKSAsXeOT1YT7bf7mUj2uogyIp2t0wbZWXjZjxJ3E7QfNrMPuZ8EyKws3qEEDuUHcYpH5d2pHbmZK7U3Rzzv52vpz2q8y3XJlR_MACjOHybiBbjErNSRj88ngXWlHbV7bqX4FRuW8FzUYQYMWNP5fhc-Bm_zSfvuZiv4yJfLumJqbVI3jqXhOq8205QgWfGR1rNZRyuOg

### probar el history
GET http://localhost:3001/api/parking-records/history?branchId=FkmFvrxmXGVpHBTiL1FiAoeuReb2
Content-Type: application/json
authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjA1NTc3MjZmYWIxMjMxZmEyZGNjNTcyMWExMDgzZGE2ODBjNGE3M2YiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcGFya2Vhc2UtMjA1ODQiLCJhdWQiOiJwYXJrZWFzZS0yMDU4NCIsImF1dGhfdGltZSI6MTc1ODc1NTEyNiwidXNlcl9pZCI6IkZrbUZ2cnhtWEdWcEhCVGlMMUZpQW9ldVJlYjIiLCJzdWIiOiJGa21GdnJ4bVhHVnBIQlRpTDFGaUFvZXVSZWIyIiwiaWF0IjoxNzU4NzU1MTI2LCJleHAiOjE3NTg3NTg3MjYsImVtYWlsIjoib3NvQHBhcmtlYXNlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJvc29AcGFya2Vhc2UuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.Qpuk1Z6JiEQN1xeR2zCGoE7wT5mCscip1L1nAPgaZd7sUG0VyANal34gMltrD4sXiq2RMgZaSEfHJm6BdJfL6wqjO9Vq0MD74ymIaVMUspDP_pRyV6XfdDQiUWdOAYbLcCWGT9F4Pbdmz5vhFYxAhoPQbq8kpgsIhUuL1Y9UonX3ralBhtib6SaOebvrxdDIuzXfPYbfUCHKVhg8QSEdrys5jP3pkCiNmKw9WnKeHDYliqdwWJWdeYAD6y0NpUtcwH3Yu7Y4d-k4tlz4vm6WC_svfhy9dFsZTfsWQCgcpekKaTEssXbIt5ePvXvr-v3HgwptGY6Jk5xJGwgbfgiXHg

